### ISSUE TITLE
Cannot update parrot os termux on non root device

### ISSUE THREAD

**Issue by asinnerm3** [sumit5011/Parrot-OS-For-Android#1]
Hello
Dunno if this is active but i run parrot os following your guide and am unable to update, getting public key not available
https://pastebin.com/m6z14hur

Anything i can do!

**Comment by sumit5011** [comment]
@asinnerm3  i will fix issue parrot OS update asap & also upload updating update process. Thank You.

**Comment by sumit5011** [comment]
@asinnerm3 issue resolved. Download Termux inbuilt bootstrap version then try to update.

Go to Repositories :

![image](https://user-images.githubusercontent.com/112896690/193186562-5c798a12-6693-469d-869f-0e00a2f19585.png)

**Comment by sumit5011** [comment]
Issue Resolved
